// This file is auto-generated by @hey-api/openapi-ts

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
	/**
	 * Detail
	 */
	detail?: Array<ValidationError>;
};

/**
 * Transaction
 */
export type Transaction = {
	/**
	 * Date
	 */
	date: string;
	/**
	 * Amount
	 */
	amount: number;
	/**
	 * Type
	 */
	type: string;
	/**
	 * Category
	 */
	category?: string | null;
	/**
	 * Description
	 */
	description?: string | null;
	/**
	 * Id
	 */
	id: number;
};

/**
 * TransactionCreate
 */
export type TransactionCreate = {
	/**
	 * Date
	 */
	date: string;
	/**
	 * Amount
	 */
	amount: number;
	/**
	 * Type
	 */
	type: string;
	/**
	 * Category
	 */
	category?: string | null;
	/**
	 * Description
	 */
	description?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
	/**
	 * Location
	 */
	loc: Array<string | number>;
	/**
	 * Message
	 */
	msg: string;
	/**
	 * Error Type
	 */
	type: string;
};

export type RootData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/";
};

export type RootResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type GetTransactionsData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/transactions/";
};

export type GetTransactionsResponses = {
	/**
	 * Response Transactions-Get Transactions
	 * Successful Response
	 */
	200: Array<Transaction>;
};

export type GetTransactionsResponse =
	GetTransactionsResponses[keyof GetTransactionsResponses];

export type AddTransactionData = {
	body: TransactionCreate;
	path?: never;
	query?: never;
	url: "/transactions/";
};

export type AddTransactionErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type AddTransactionError =
	AddTransactionErrors[keyof AddTransactionErrors];

export type AddTransactionResponses = {
	/**
	 * Successful Response
	 */
	200: Transaction;
};

export type AddTransactionResponse =
	AddTransactionResponses[keyof AddTransactionResponses];

export type DeleteTransactionData = {
	body?: never;
	path: {
		/**
		 * Tx Id
		 */
		tx_id: number;
	};
	query?: never;
	url: "/transactions/{tx_id}";
};

export type DeleteTransactionErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type DeleteTransactionError =
	DeleteTransactionErrors[keyof DeleteTransactionErrors];

export type DeleteTransactionResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type UpdateTransactionData = {
	body: TransactionCreate;
	path: {
		/**
		 * Tx Id
		 */
		tx_id: number;
	};
	query?: never;
	url: "/transactions/{tx_id}";
};

export type UpdateTransactionErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type UpdateTransactionError =
	UpdateTransactionErrors[keyof UpdateTransactionErrors];

export type UpdateTransactionResponses = {
	/**
	 * Successful Response
	 */
	200: Transaction;
};

export type UpdateTransactionResponse =
	UpdateTransactionResponses[keyof UpdateTransactionResponses];

export type ClientOptions = {
	baseUrl: `${string}://${string}` | (string & {});
};
